# Generated by Django 4.2.29 on 2026-03-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0003_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Meeting",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
