# Generated by Django 4.2.29 on 2026-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0005_meeting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Meeting",
        ),
    ]
